set(glew-cmake_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(glew-cmake_BUILD_STATIC ON CACHE BOOL "" FORCE)
add_subdirectory(${PROJECT_DEPENDENCIES_DIR}/glew-2.2.0 ${PROJECT_DEPENDENCIES_BUILD_DIR}/glew-2.2.0)
